// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.example.tutorial {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  import com.example.tutorial.Person;
  public final class AddressBook extends Message {
    public function AddressBook() {
      registerField("person","com.example.tutorial.Person",Descriptor.MESSAGE,Descriptor.LABEL_REPEATED,1);
    }
    // repeated .tutorial.Person person = 1;
    public var person:Array = new Array();
    
    //fix bug 1 protobuf-actionscript3
    //dummy var using com.example.tutorial necessary to avoid following exception
    //ReferenceError: Error #1065: Variable NetworkInfo is not defined.
    //at global/flash.utils::getDefinitionByName()
    //at com.google.protobuf::Message/readFromCodedStream()[/Users/philippepascal/Work/workspaceMotorola/BlurCom/lib/com/google/protobuf/Message.as:112]
    private var personDummy:com.example.tutorial.Person = null;
    
  
  }
}